In [1]:
import pandas as pd

In [17]:
lky_data = pd.read_csv("LouisvilleClean.csv")
lky_data

,Unnamed: 0,PrimaryColor,PrimaryBreed,IntakeInternalStatus,IntakeAsilomarStatus,ReproductiveStatusAtIntake,OutcomeType,AgeInMonths,DurationInShelter,BreedCategory,Pet_age_category,Binary_outcome,Sex
0,4,WHITE,PIT BULL TERRIER,NORMAL,HEALTHY,FERTILE,EUTH,12.17,29.0,Pure,Young,Deny,Male
1,51,BLACK,BORDER COLLIE,NORMAL,HEALTHY,ALTERED,ADOPTION,10.17,108.0,Mix,Young,Take,Female
2,69,TAN,GOLDEN RETRIEVER,NORMAL,HEALTHY,ALTERED,ADOPTION,23.43,56.0,Mix,Young,Take,Male
3,99,WHITE,LABRADOR RETRIEVER,NORMAL,HEALTHY,ALTERED,ADOPTION,0.17,183.0,Pure,Baby,Take,Female
4,103,BLACK,PIT BULL TERRIER,SICK,HEALTHY,FERTILE,EUTH,11.90,0.0,Pure,Young,Deny,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42817,150835,APRICOT,DANDIE DINMONT TERRIER,NORMAL,HEALTHY,FERTILE,ADOPTION,36.53,109.0,Mix,Adult,Take,Male
42818,150836,BLACK,DACHSHUND - WIREHAIRED,NORMAL,HEALTHY,FERTILE,ADOPTION,36.53,71.0,Pure,Adult,Take,Female
42819,150837,YELLOW BRINDLE,GREYHOUND,NORMAL,HEALTHY,FERTILE,ADOPTION,24.13,140.0,Mix,Adult,Take,Male
42820,150838,CREAM,CAIRN TERRIER,NORMAL,HEALTHY,FERTILE,ADOPTION,7.07,7.0,Pure,Young,Take,Female
42821,150839,BLACK,MINIATURE PINSCHER,NORMAL,HEALTHY,ALTERED,TRANSFER,51.30,8.0,Pure,Adult,Deny,Male

In [18]:
df = lky_data.drop(columns=['Unnamed: 0',
                       'IntakeInternalStatus', 
                       'IntakeAsilomarStatus', 
                       'ReproductiveStatusAtIntake',
                       'AgeInMonths',
                        'DurationInShelter',
                        'Binary_outcome'])
df

,PrimaryColor,PrimaryBreed,OutcomeType,BreedCategory,Pet_age_category,Sex
0,WHITE,PIT BULL TERRIER,EUTH,Pure,Young,Male
1,BLACK,BORDER COLLIE,ADOPTION,Mix,Young,Female
2,TAN,GOLDEN RETRIEVER,ADOPTION,Mix,Young,Male
3,WHITE,LABRADOR RETRIEVER,ADOPTION,Pure,Baby,Female
4,BLACK,PIT BULL TERRIER,EUTH,Pure,Young,Male
...,...,...,...,...,...,...
42817,APRICOT,DANDIE DINMONT TERRIER,ADOPTION,Mix,Adult,Male
42818,BLACK,DACHSHUND - WIREHAIRED,ADOPTION,Pure,Adult,Female
42819,YELLOW BRINDLE,GREYHOUND,ADOPTION,Mix,Adult,Male
42820,CREAM,CAIRN TERRIER,ADOPTION,Pure,Young,Female
42821,BLACK,MINIATURE PINSCHER,TRANSFER,Pure,Adult,Male

In [45]:
df.PrimaryBreed.unique()

array(['PIT BULL TERRIER', 'BORDER COLLIE', 'GOLDEN RETRIEVER',
       'LABRADOR RETRIEVER', 'ST BERNARD', 'WIRE-HAIRED POINTING GRIFFON',
       'BEAGLE', 'PLOTT HOUND', 'BICHON FRISE', 'GERMAN SHEPHERD DOG',
       'TIBETAN TERRIER', 'SHETLAND SHEEPDOG', 'JACK RUSS TER', 'PUG',
       'MANCHESTER TERRIER', 'CHIHUAHUA', 'PEKINGESE', 'CHOW CHOW',
       'PARSON (JACK) RUSSELL TERRIER', 'IRISH TERRIER', 'BASSET HOUND',
       'ROTTWEILER', 'FRENCH BULLDOG', 'FOX TERRIER', 'SIBERIAN HUSKY',
       'POMERANIAN', 'BOXER', 'RAT TERRIER', 'GREAT DANE', 'POODLE - TOY',
       'AMERICAN STAFFORDSHIRE TERRIER', 'SCHNAUZER - MINIATURE',
       'AUSTRALIAN SHEPHERD', 'WEIMARANER', 'DOBERMAN PINSCHER',
       'MASTIFF', 'SHIH TZU', 'FINNISH SPITZ', 'POODLE - MINIATURE',
       'BOSTON TERRIER', 'YORKSHIRE TERRIER', 'AMERICAN BULLDOG',
       'MINIATURE PINSCHER', 'BLACK AND TAN COONOUND', 'COCKER SPANIEL',
       'CAIRN TERRIER', 'TOY FOX TERRIER', 'POINTER', 'AIREDALE TERRIER',
       'BULL TERRIER', 'DACHSHUND', 'REDBONE COONHOUND', 'GREAT PYRENEES',
       'WELSH CORGI - PEMBROKE', 'WELSH CORGI - CARDIGAN', 'AKITA',
       'SWISS HOUND', 'BRUSSELS GRIFFON', 'AUSTRALIAN CATTLE DOG',
       'SHIBA INU', 'ENGLISH SPRINGER SPANIEL', 'CHINESE SHARPEI',
       'DALMATIAN', 'ALASKAN HUSKY', 'COLLIE', 'OTTERHOUND',
       'POODLE - STANDARD', 'BLOODHOUND', 'PHARAOH HOUND', 'NEWFOUNDLAND',
       'ENGLISH SETTER', 'BELGIAN MALINOIS', 'BORDER TERRIER', 'MIX',
       'AMERICAN FOXHOUND', 'ALASKAN MALAMUTE', 'OLD ENGLISH SHEEPDOG',
       'AMERICAN ESKIMO', 'IRISH WOLFHOUND', 'TREEING CUR',
       'DANDIE DINMONT TERRIER', 'HAVANESE', 'HARRIER', 'WELSH TERRIER',
       'TREEING WALKER COONHOUND', 'SCOTTISH TERRIER', 'LHASA APSO',
       'WEST HIGHLAND WHITE TERRIER', 'COCKER-POO', 'SAMOYED',
       'SCHNAUZER - STANDARD', 'MALTESE', 'CANE CORSO',
       'CATAHOULA LEOPARD HOUND', 'GERMAN SHORTHAIRED POINTER',
       'SCHIPPERKE', 'KEESHOND', 'ENGLISH BULLDOG', 'PATTERDALE TERRIER',
       'ENGLISH POINTER', 'RHODESIAN RIDGEBACK', 'GORDON SETTER',
       'NORWEGIAN ELKHOUND', 'SILKY TERRIER', 'BULLDOG',
       'NORFOLK TERRIER', 'PRESA CANARIO', 'NORWICH TERRIER',
       'DOGO ARGENTINO', 'FEIST', 'FLAT-COATED RETRIEVER', 'BRIARD',
       'ANATOLIAN SHEPHERD', 'BERNESE HOUND', 'IRISH SETTER',
       'BEARDED COLLIE', 'ENGLISH FOXHOUND', 'CAROLINA DOG', 'WHIPPET',
       'BASENJI', 'SCHNAUZER - GIANT', 'JAPANESE CHIN', 'GREYHOUND',
       'BLUETICK COONHOUND', 'WOLF HYBRID', 'KARELIAN BEAR DOG',
       'ENGLISH COCKER SPANIEL', 'PAPILLON', 'BULLMASTIFF',
       'PETIT BASSET GRIFFON VENDEEN', 'CAVALIER KING CHARLES SPANIEL',
       'BLACK MOUTH CUR', 'BELGIAN SHEEPDOG', 'CLUMBER SPANIEL',
       'BRITTANY', 'BERNESE MOUNTAIN DOG', 'CHINESE CRESTED DOG',
       'SOFT-COATED WHEATEN TERRIER', 'AUSTRALIAN TERRIER',
       'AFFENPINSCHER', 'SPINONE ITALIANO', 'ITALIAN GREYHOUND',
       'PORTUGUESE WATER DOG', 'ENGLISH COONHOUND (REDTICK COONHOUND)',
       'BOYKIN SPANIEL', 'HOVAWART', 'BELGIAN TERVUREN',
       'OLD ENGLISH BULLDOG', 'SALUKI', 'UNKNOWN', 'PEKAPOO',
       'SKYE TERRIER', 'COONHOUND', 'TIBETAN SPANIEL',
       'GREATER SWISS MOUNTAIN DOG', 'ENGLISH TOY SPANIEL',
       'CHESAPEAKE BAY RETRIEVER', 'KOREAN JINDO', 'VIZSLA',
       'AUSTRALIAN KELPIE', 'DOGUE DE BORDEAUX', 'WELSH SPRINGER SPANIEL',
       'FIELD SPANIEL', 'PICARDY SHEEPDOG', 'HOUND', 'IBIZAN HOUND',
       'POLISH LOWLAND SHEEPDOG', 'FILA BRASILEIRO', 'ENGLISH SHEPHERD',
       'GERMAN PINSCHER', 'SPANISH WATER DOG', 'TIBETAN MASTIFF',
       'NEAPOLITAN MASTIFF', 'BEAUCERON', 'BEDLINGTON TERRIER',
       'GLEN OF IMAAL TERRIER', 'TERRIER', 'BORZOI', 'CANAAN DOG',
       'LOWCHEN', 'GERMAN WIREHAIRED POINTER',
       'TENNESEE TREEING BRINDLE HOUND', 'DUTCH SHEPHERD',
       'BULL TERRIER - MINIATURE', 'LANDSEER', 'SUSSEX SPANIEL',
       'SCOTTISH DEERHOUND', 'BOUVIER DES FLANDRES', 'LEONBERGER',
       'BOERBOEL', 'NORWEGIAN BUHUND', 'COTON DE TULEAR',
       'NOVA SCOTIA DUCK-TOLLING RETRIEVER', 'ALASKAN KLEE KAI',
       'MUNSTERLANDER', 'PULI', 'PODENGO PORTUGUESO PEQUENO'],
      dtype=object)

In [46]:
breed_counts = df.PrimaryBreed.value_counts()
breed_counts.head(30)

PIT BULL TERRIER                  8298
LABRADOR RETRIEVER                5080
BEAGLE                            2966
GERMAN SHEPHERD DOG               2897
CHIHUAHUA                         2146
BOXER                             1698
SHIH TZU                          1119
ROTTWEILER                        1108
BORDER COLLIE                      916
JACK RUSS TER                      915
CHOW CHOW                          909
DACHSHUND                          667
POODLE - MINIATURE                 612
YORKSHIRE TERRIER                  605
AUSTRALIAN SHEPHERD                515
SIBERIAN HUSKY                     509
POMERANIAN                         496
AMERICAN STAFFORDSHIRE TERRIER     447
COCKER SPANIEL                     439
PUG                                438
MINIATURE PINSCHER                 422
GOLDEN RETRIEVER                   417
AUSTRALIAN CATTLE DOG              376
SCHNAUZER - MINIATURE              347
AMERICAN BULLDOG                   338
COLLIE                             329
RAT TERRIER                        321
BASSET HOUND                       316
PARSON (JACK) RUSSELL TERRIER      278
BOSTON TERRIER                     247
Name: PrimaryBreed, dtype: int64

In [21]:
df.loc[df['PrimaryBreed'].str.contains('AMERICAN STAFFORDSHIRE TERRIER'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('AMERICAN STAFFORDSHIRE TERRIER'), 'PrimaryBreed'].str.replace('AMERICAN STAFFORDSHIRE TERRIER', 'STAFFORDSHIRE')

In [22]:
df.loc[df['PrimaryBreed'].str.contains('STAFFORDSHIRE'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('STAFFORDSHIRE'), 'PrimaryBreed'].str.replace('STAFFORDSHIRE', 'AMERICAN STAFFORDSHIRE TERRIER')

In [34]:
df.loc[df['PrimaryBreed'].str.contains('AMERICAN STAFFORDSHIRE TERRIER BULL TERRIER'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('AMERICAN STAFFORDSHIRE TERRIER BULL TERRIER'), 'PrimaryBreed'].str.replace('AMERICAN STAFFORDSHIRE TERRIER BULL TERRIER', 'AMERICAN STAFFORDSHIRE TERRIER')

In [23]:
df.loc[df['PrimaryBreed'].str.contains('AMERICAN PIT BULL TERRIER'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('AMERICAN PIT BULL TERRIER'), 'PrimaryBreed'].str.replace('AMERICAN PIT BULL TERRIER', 'PIT BULL TERRIER')

In [24]:
df.loc[df['PrimaryBreed'].str.contains('QUEENSLAND HEELER'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('QUEENSLAND HEELER'), 'PrimaryBreed'].str.replace('QUEENSLAND HEELER', 'AUSTRALIAN CATTLE DOG')

In [25]:
df.loc[df['PrimaryBreed'].str.contains('CHIHUAHUA - SMOOTH COATED'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('CHIHUAHUA - SMOOTH COATED'), 'PrimaryBreed'].str.replace('CHIHUAHUA - SMOOTH COATED', 'CHIHUAHUA')
df.loc[df['PrimaryBreed'].str.contains('CHIHUAHUA - LONG HAIRED'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('CHIHUAHUA - LONG HAIRED'), 'PrimaryBreed'].str.replace('CHIHUAHUA - LONG HAIRED', 'CHIHUAHUA')

In [37]:
df.loc[df['PrimaryBreed'].str.contains('FOX TERRIER - WIREHAIRED'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('FOX TERRIER - WIREHAIRED'), 'PrimaryBreed'].str.replace('FOX TERRIER - WIREHAIRED', 'FOX TERRIER')
df.loc[df['PrimaryBreed'].str.contains('FOX TERRIER - SMOOTH'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('FOX TERRIER - SMOOTH'), 'PrimaryBreed'].str.replace('FOX TERRIER - SMOOTH', 'FOX TERRIER')

In [38]:
df.loc[df['PrimaryBreed'].str.contains('COLLIE - ROUGH'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('COLLIE - ROUGH'), 'PrimaryBreed'].str.replace('COLLIE - ROUGH', 'COLLIE')
df.loc[df['PrimaryBreed'].str.contains('COLLIE - SMOOTH'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('COLLIE - SMOOTH'), 'PrimaryBreed'].str.replace('COLLIE - SMOOTH', 'COLLIE')

In [42]:
df.loc[df['PrimaryBreed'].str.contains('ST BERNARD - ROUGH COATED'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('ST BERNARD - ROUGH COATED'), 'PrimaryBreed'].str.replace('ST BERNARD - ROUGH COATED', 'ST BERNARD')
df.loc[df['PrimaryBreed'].str.contains('ST BERNARD - SMOOTH COATED'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('ST BERNARD - SMOOTH COATED'), 'PrimaryBreed'].str.replace('ST BERNARD - SMOOTH COATED', 'ST BERNARD')

In [44]:
df.loc[df['PrimaryBreed'].str.contains('DACHSHUND - LONGHAIRED'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('DACHSHUND - LONGHAIRED'), 'PrimaryBreed'].str.replace('DACHSHUND - LONGHAIRED', 'DACHSHUND')
df.loc[df['PrimaryBreed'].str.contains('DACHSHUND - WIREHAIRED'), 'PrimaryBreed'] = df.loc[df['PrimaryBreed'].str.contains('DACHSHUND - WIREHAIRED'), 'PrimaryBreed'].str.replace('DACHSHUND - WIREHAIRED', 'DACHSHUND')